import {
  MODEL_GEMINI_2_5_FLASH_LITE,
  MODEL_GEMINI_2_5_FLASH,
  MODEL_GEMINI_2_5_FLASH_LITE_PREVIEW_06_17,
  MODEL_GEMINI_2_5_PRO,
  MODEL_GEMINI_2_0_FLASH_LITE,
  MODEL_GEMINI_2_0_FLASH,
} from '@aituber-onair/core';

// Gemini models list
export const geminiModels = [
  MODEL_GEMINI_2_5_FLASH_LITE,
  MODEL_GEMINI_2_5_FLASH,
  MODEL_GEMINI_2_5_FLASH_LITE_PREVIEW_06_17,
  MODEL_GEMINI_2_5_PRO,
  MODEL_GEMINI_2_0_FLASH_LITE,
  MODEL_GEMINI_2_0_FLASH,
];
